// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBEy_OaEe_4aNyq6YOYUtudinmOd130XU',
    appId: '1:162433698947:web:ec9b8098f96848988e9fb6',
    messagingSenderId: '162433698947',
    projectId: 'rentalapp-fd6f1',
    authDomain: 'rentalapp-fd6f1.firebaseapp.com',
    storageBucket: 'rentalapp-fd6f1.firebasestorage.app',
    measurementId: 'G-3MH8WCM0W1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBEy_OaEe_4aNyq6YOYUtudinmOd130XU',
    appId: '1:162433698947:android:YOUR_ANDROID_APP_ID',
    messagingSenderId: '162433698947',
    projectId: 'rentalapp-fd6f1',
    storageBucket: 'rentalapp-fd6f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBEy_OaEe_4aNyq6YOYUtudinmOd130XU',
    appId: '1:162433698947:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '162433698947',
    projectId: 'rentalapp-fd6f1',
    storageBucket: 'rentalapp-fd6f1.firebasestorage.app',
    iosBundleId: 'com.example.rentalapp',
  );
}